title: 神戸市西区
description: 神戸市西区内でテイクアウトできるお店
data_url: https://docs.google.com/spreadsheets/d/1thON-5NuL0XX3RybSq0Twp9YLzBvaUh936oMihx48Cs/export?format=csv&gid=0
repository: https://github.com/iemeshi/kobe-nishiku/
form_url: https://docs.google.com/forms/d/e/1FAIpQLSd_UAfKF_V-NGS-fxp92ufxG1lz0XcUEPsr4zX92Pqqymg8ig/viewform?usp=sf_link
